//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogThisWebApplication.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name someValue from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SomeFunction", ReplyAction="*")]
        LogThisWebApplication.WebService.SomeFunctionResponse SomeFunction(LogThisWebApplication.WebService.SomeFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SomeFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<LogThisWebApplication.WebService.SomeFunctionResponse> SomeFunctionAsync(LogThisWebApplication.WebService.SomeFunctionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SomeFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SomeFunction", Namespace="http://tempuri.org/", Order=0)]
        public LogThisWebApplication.WebService.SomeFunctionRequestBody Body;
        
        public SomeFunctionRequest() {
        }
        
        public SomeFunctionRequest(LogThisWebApplication.WebService.SomeFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SomeFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string someValue;
        
        public SomeFunctionRequestBody() {
        }
        
        public SomeFunctionRequestBody(string someValue) {
            this.someValue = someValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SomeFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SomeFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LogThisWebApplication.WebService.SomeFunctionResponseBody Body;
        
        public SomeFunctionResponse() {
        }
        
        public SomeFunctionResponse(LogThisWebApplication.WebService.SomeFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SomeFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SomeFunctionResult;
        
        public SomeFunctionResponseBody() {
        }
        
        public SomeFunctionResponseBody(string SomeFunctionResult) {
            this.SomeFunctionResult = SomeFunctionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : LogThisWebApplication.WebService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<LogThisWebApplication.WebService.WebService1Soap>, LogThisWebApplication.WebService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogThisWebApplication.WebService.SomeFunctionResponse LogThisWebApplication.WebService.WebService1Soap.SomeFunction(LogThisWebApplication.WebService.SomeFunctionRequest request) {
            return base.Channel.SomeFunction(request);
        }
        
        public string SomeFunction(string someValue) {
            LogThisWebApplication.WebService.SomeFunctionRequest inValue = new LogThisWebApplication.WebService.SomeFunctionRequest();
            inValue.Body = new LogThisWebApplication.WebService.SomeFunctionRequestBody();
            inValue.Body.someValue = someValue;
            LogThisWebApplication.WebService.SomeFunctionResponse retVal = ((LogThisWebApplication.WebService.WebService1Soap)(this)).SomeFunction(inValue);
            return retVal.Body.SomeFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogThisWebApplication.WebService.SomeFunctionResponse> LogThisWebApplication.WebService.WebService1Soap.SomeFunctionAsync(LogThisWebApplication.WebService.SomeFunctionRequest request) {
            return base.Channel.SomeFunctionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogThisWebApplication.WebService.SomeFunctionResponse> SomeFunctionAsync(string someValue) {
            LogThisWebApplication.WebService.SomeFunctionRequest inValue = new LogThisWebApplication.WebService.SomeFunctionRequest();
            inValue.Body = new LogThisWebApplication.WebService.SomeFunctionRequestBody();
            inValue.Body.someValue = someValue;
            return ((LogThisWebApplication.WebService.WebService1Soap)(this)).SomeFunctionAsync(inValue);
        }
    }
}
