USE [master]
GO
/****** Object:  Database [LRAPTesterDatabase]    Script Date: 29/05/2017 13:43:44 ******/
CREATE DATABASE [LRAPTesterDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LRAPTesterDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LRAPTesterDatabase.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LRAPTesterDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LRAPTesterDatabase_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [LRAPTesterDatabase] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LRAPTesterDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LRAPTesterDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET ARITHABORT OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [LRAPTesterDatabase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LRAPTesterDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LRAPTesterDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LRAPTesterDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LRAPTesterDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET RECOVERY FULL 
GO
ALTER DATABASE [LRAPTesterDatabase] SET  MULTI_USER 
GO
ALTER DATABASE [LRAPTesterDatabase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LRAPTesterDatabase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LRAPTesterDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LRAPTesterDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [LRAPTesterDatabase]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 29/05/2017 13:43:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_Person_ID]  DEFAULT (newid()),
	[Name] [nvarchar](max) NOT NULL,
	[Address] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [LRAPTesterDatabase] SET  READ_WRITE 
GO
